### PR TITLE
test: Add basic CI and some improvements

### PR DESCRIPTION
**Pull request by jcs090218**
Hi, Jeff!

This is Jen-Chieh from SF Emacs meetup! :) I would like to help a little since I really like your package! This PR does the following:

- Add autoload
- Add basic CI, see test result in https://github.com/jcs-PR/tspew/actions/runs/6181525527?pr=1. **(There is currently a bug from the Windows snapshot; I've added experimental flags so we can just ignore that. Badge will still be green [CI](https://github.com/jcs-PR/tspew/actions/workflows/test.yml))**
- Clarify installation method

BTW, I have added this package to my own ELPA so anyone can install it through [JCS-ELPA](https://github.com/jefftrull/tspew/compare/master...jcs-PR:tspew:test/eask) now! :D

[JCS-ELPA](https://jcs-emacs.github.io/jcs-elpa/#/tspew)

### CODE REVIEW

**Comment by jefftrull** [comment]
Wow, this is amazing! I didn't know you were even aware of this work :) Honestly this code is very raw right now and has only recently started working enough to publicize. I don't even have unit tests...

**Comment by jcs090218** [comment]
I was looking at the Boost library (my school requires us to do that), and I've also taken a look at the `wave` library you maintain! :D Then I was curious about your recent activities; that's how I got here!

> Honestly this code is very raw right now and has only recently started working enough to publicize.

No worries. My ELPA is generally for development use for now! ;)

> I don't even have unit tests...

You can set up unit tests easily with Eask. :grin:

**Comment by jefftrull** [comment]
I think I want to split these changes up a little :)
- fix formatting
- autoload
- clean package stuff (headers, lexical-binding, provide)
- eask/CI stuff, which I don't yet understand

If it's OK with you I'll fix 1-3 in my own commits and mention that you called them out. Item 4 I need to understand better first though.

**Comment by jefftrull** [comment]
Also, if I understand how autoload works correctly, to use autoload properly I need to make tspew a package - and so item 2 ("autoload") and the eask stuff you have proposed are connected.

**Comment by jcs090218** [comment]
> Also, if I understand how autoload works correctly, to use autoload properly I need to make tspew a package - and so item 2 ("autoload") and the eask stuff you have proposed are connected.

Yes, so in your init.el you can just do:

```elisp
(add-hook 'compilation-mode-hook #'tspew-mode)
```

without `(require 'tspew-mode)`.

Right now eask only does three things.

1. Package to tar (test to see if package can be packaged correctly)
2. Install built tar (test to see if package can be installed correctly)
3. Byte compile test (the same as `M-x byte-compile-file`)

Here are something that you might want to fix, see https://github.com/jcs-PR/tspew/actions/runs/6181525527/job/16779640634?pr=1#step:5:75

```
In tspew--format-quoted-expr:
tspew.el:388:2: Warning: docstring wider than 80 characters

In tspew--handle-quoted-expr:
tspew.el:446:2: Warning: docstring wider than 80 characters
tspew.el:449:10: Warning: Unused lexical variable ‘ov’

In tspew--parse-initialize:
tspew.el:659:33: Warning: Unused lexical argument ‘proc’

In tspew--parse-template-preamble:
Warning: docstring wider than 80 characters

In tspew--parse-with-clause:
Warning: docstring wider than 80 characters

In tspew--parser-paren-expr:
tspew.el:804:2: Warning: docstring wider than 80 characters

In tspew--parser-alternative:
Warning: macro ‘tspew--parser-alternative’ defined too late
tspew.el:842:2: Warning: docstring wider than 80 characters

In tspew--parser-sequential:
Warning: docstring wider than 80 characters

In tspew--parse-func-name:
Warning: docstring wider than 80 characters

In tspew--parse-param-list:
Warning: docstring wider than 80 characters

In tspew--parser-builtin-int-type:
Warning: docstring wider than 80 characters
```

**Comment by jefftrull** [comment]
I created a branch off of yours and merged my recent changes, resolving the conflicts. It's jcs-PR-sync in case that helps

**Comment by jcs090218** [comment]
I've rebased it (on the website). See if that works? :)

BTW, you don't have to merge this if you already have the idea! 👍

**Comment by jcs090218** [comment]
I've added the `compat` to this PR, and it does seems to solve the issue. :)

Once again, you don't have to merge this if you don't want Eask to be in your project! 😉

**Pull request closed without merging**
